version: '3.8'

services:
  n8n_chatbot_emocional:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_GOOGLE_API_KEY=${REACT_APP_GOOGLE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs: 