version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_GOOGLE_API_KEY=${REACT_APP_GOOGLE_API_KEY}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs: 